# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4046727bb86767bffe26aa504b1189b9f81cb02120520cf5e101ac9a991c8ae6632b235d9efe4e07cdd4cacef4c7473848226caeac5f2835f3f8579d555c3b46

test:
  secret_key_base: 76fca732f0d740f59f7d79801fd6d1feb62ea94ac3d1a5817e1f785581698f5a17b816b1c18641612c1dacdf24a0d2f85b617cf71557ed3c587b2b4d5c958b59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
